# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'streamFS.ui'
#
# Created: Tue May 25 23:06:24 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comandInput = QtGui.QLineEdit(self.centralwidget)
        self.comandInput.setGeometry(QtCore.QRect(20, 20, 231, 20))
        self.comandInput.setObjectName("comandInput")
        self.updateButton = QtGui.QPushButton(self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(20, 480, 91, 20))
        self.updateButton.setObjectName("updateButton")
        self.statusView = QtGui.QTextBrowser(self.centralwidget)
        self.statusView.setGeometry(QtCore.QRect(430, 250, 341, 211))
        self.statusView.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.statusView.setObjectName("statusView")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(380, 20, 16, 441))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 520, 791, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(True)
        self.progressBar.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.progressBar.setObjectName("progressBar")
        self.runButton = QtGui.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(270, 20, 75, 20))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("monkey_on_16x16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runButton.setIcon(icon)
        self.runButton.setObjectName("runButton")
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 300, 331, 161))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setVisible(False)
        self.treeView = QtGui.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(20, 60, 331, 192))
        self.treeView.setObjectName("treeView")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 260, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.targetImage = QtGui.QLineEdit(self.centralwidget)
        self.targetImage.setGeometry(QtCore.QRect(80, 260, 271, 21))
        self.targetImage.setCursor(QtCore.Qt.ArrowCursor)
        self.targetImage.setAutoFillBackground(False)
        self.targetImage.setStyleSheet("background-color: rgb(212, 208, 200);")
        self.targetImage.setFrame(False)
        self.targetImage.setReadOnly(True)
        self.targetImage.setObjectName("targetImage")
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(430, 210, 341, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.fsInfoText = QtGui.QTextEdit(self.centralwidget)
        self.fsInfoText.setGeometry(QtCore.QRect(430, 20, 341, 171))
        self.fsInfoText.setAutoFillBackground(False)
        self.fsInfoText.setStyleSheet("color: rgb(212, 208, 200);\n"
"background-color: rgb(212, 208, 200);")
        self.fsInfoText.setFrameShape(QtGui.QFrame.Box)
        self.fsInfoText.setFrameShadow(QtGui.QFrame.Plain)
        self.fsInfoText.setAutoFormatting(QtGui.QTextEdit.AutoBulletList)
        self.fsInfoText.setReadOnly(True)
        self.fsInfoText.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.fsInfoText.setObjectName("fsInfoText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("monkey_off_16x16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon1)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.updateButton.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.runButton.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Target:", None, QtGui.QApplication.UnicodeUTF8))
        self.fsInfoText.setDocumentTitle(QtGui.QApplication.translate("MainWindow", "File System Info", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

